name: flutter_location
description: A new flutter plugin project.
version: 0.0.6
author: Javier Elizaga <javier.elizaga@gmail.com>
homepage: https://github.com/javier-elizaga/flutter-location

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.example.flutterlocation
    pluginClass: FlutterLocationPlugin
